#!/bin/sh
# Precommit hook to rebuild generated go code. Fails if building or copying the
# files fails.
set -e
bazel build build/bazel/remote/execution/v2:remote_execution_go_proto \
      build/bazel/remote/asset/v1:remote_asset_go_proto \
      build/bazel/remote/logstream/v1:remote_logstream_go_proto

for i in "build/bazel/remote/execution/v2/remote_execution.pb.go" \
	 "build/bazel/semver/semver.pb.go" \
	 "build/bazel/remote/asset/v1/remote_asset.pb.go" \
	 "build/bazel/remote/logstream/v1/remote_logstream.pb.go" ; do
    cp "$(find $(bazel info bazel-bin) -path "*/$i")" "$i"
    git add "$i"
done
